
on:
    workflow_dispatch:

env:
    client_secret: ${{ secrets.MY_API_KEY }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: instal pip packet
        run: pip install os
      - name: Run my script
        run: python t.py
